import { StudentGroup, SystemAlert, UserSettings, RiskLevel } from './types';

/**
 * Calculates the overall project health score (0 to 100) using 5 weighted factors:
 * 1. Task Completion (30%) - Percentage of tasks marked as completed in Asana
 * 2. On-Time Delivery (25%) - Measures task timeliness, lower score if tasks are overdue
 * 3. Member Activity (20%) - Code updates, commits, and task participation
 * 4. Fair Work Share (15%) - How evenly work is divided across team members
 * 5. Team Communication (10%) - Message exchange and collaboration in workspace
 */
export function calculateHealthScore(scores: {
  taskCompletionScore: number;
  overdueTaskScore: number;
  memberActivityScore: number;
  workloadEquityScore: number;
  communicationScore: number;
}): number {
  // Step 1: Multiply each factor by its assigned weight percentage
  const weightedSum =
    scores.taskCompletionScore * 0.30 +
    scores.overdueTaskScore * 0.25 +
    scores.memberActivityScore * 0.20 +
    scores.workloadEquityScore * 0.15 +
    scores.communicationScore * 0.10;

  // Step 2: Keep the score clamped between 0 and 100, rounded to 1 decimal place
  const clampedScore = Math.max(0, Math.min(100, weightedSum));
  return Math.round(clampedScore * 10) / 10;
}

/**
 * Categorizes the project risk based on the health score:
 * - Low Risk (70 - 100): Project is healthy and on track
 * - Medium Risk (40 - 69): Needs monitoring, some delays or imbalances
 * - High Risk (0 - 39): Needs urgent help, multiple overdue tasks
 */
export function getRiskClassification(healthScore: number): RiskLevel {
  if (healthScore >= 70) return 'Low';
  if (healthScore >= 40) return 'Medium';
  return 'High';
}

export const INITIAL_GROUPS: StudentGroup[] = [
  {
    id: 'grp-1',
    name: 'Team Nova',
    projectTitle: 'Autonomous Drone Fleet Dispatcher & Path Planner',
    courseCode: 'CS401',
    courseName: 'Capstone Software Engineering',
    lastActivity: '4 hours ago',
    lastActivityTimestamp: '2026-10-03T02:15:00Z',
    teamLeader: 'Alex Rivera',
    repoUrl: 'github.com/eecs-cs401/team-nova-fleet',
    asanaWorkspace: 'CS401-Team-Nova',
    taskCompletionScore: 45,
    overdueTaskScore: 20,
    memberActivityScore: 35,
    workloadEquityScore: 25,
    communicationScore: 30,
    members: [
      {
        id: 'm1',
        name: 'Alex Rivera',
        email: 'a.rivera@university.edu',
        role: 'Full Stack & Tech Lead',
        avatarColor: 'bg-indigo-600',
        assignedTasks: 16,
        completedTasks: 13,
        commits: 54,
        prReviews: 12,
        messagesSent: 48,
        lastActive: '4 hours ago',
        workloadSharePercent: 68,
        status: 'Overloaded',
      },
      {
        id: 'm2',
        name: 'Jordan Lee',
        email: 'j.lee@university.edu',
        role: 'Algorithms & Waypoints',
        avatarColor: 'bg-rose-500',
        assignedTasks: 5,
        completedTasks: 1,
        commits: 2,
        prReviews: 0,
        messagesSent: 4,
        lastActive: '8 days ago',
        workloadSharePercent: 8,
        status: 'At-Risk / Disengaged',
      },
      {
        id: 'm3',
        name: 'Priya Patel',
        email: 'p.patel@university.edu',
        role: 'Frontend UI & Telemetry',
        avatarColor: 'bg-amber-500',
        assignedTasks: 7,
        completedTasks: 3,
        commits: 11,
        prReviews: 3,
        messagesSent: 16,
        lastActive: '2 days ago',
        workloadSharePercent: 14,
        status: 'Balanced',
      },
      {
        id: 'm4',
        name: 'Marcus Zhang',
        email: 'm.zhang@university.edu',
        role: 'Hardware Simulation & QA',
        avatarColor: 'bg-emerald-600',
        assignedTasks: 6,
        completedTasks: 2,
        commits: 8,
        prReviews: 2,
        messagesSent: 9,
        lastActive: '3 days ago',
        workloadSharePercent: 10,
        status: 'Balanced',
      },
    ],
    tasks: [
      {
        id: 't-101',
        title: 'Implement Kalman Filter for GPS drift compensation',
        assigneeId: 'm2',
        assigneeName: 'Jordan Lee',
        dueDate: 'Sep 24, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-102',
        title: 'Collision avoidance mesh protocol v1',
        assigneeId: 'm2',
        assigneeName: 'Jordan Lee',
        dueDate: 'Sep 28, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 12,
      },
      {
        id: 't-103',
        title: 'Telemetry dashboard real-time WebSocket connection',
        assigneeId: 'm1',
        assigneeName: 'Alex Rivera',
        dueDate: 'Oct 01, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 10,
      },
      {
        id: 't-104',
        title: 'Battery exhaustion emergency landing protocol',
        assigneeId: 'm4',
        assigneeName: 'Marcus Zhang',
        dueDate: 'Oct 02, 2026',
        status: 'Overdue',
        priority: 'Medium',
        weight: 8,
      },
      {
        id: 't-105',
        title: 'Interactive 3D flight corridor visualization',
        assigneeId: 'm3',
        assigneeName: 'Priya Patel',
        dueDate: 'Oct 06, 2026',
        status: 'In Progress',
        priority: 'Medium',
        weight: 8,
      },
    ],
    riskFactors: [
      {
        id: 'rf-1',
        title: 'Overdue Critical Path Deliverables',
        description: '3 high-priority sprint tasks overdue by an average of 7.2 days, blocking telemetry testing.',
        severity: 'Critical',
        scoreImpact: -18.5,
        suggestedAction: 'Convene immediate sprint recovery meeting with Jordan and Alex.',
      },
      {
        id: 'rf-2',
        title: 'Severe Workload Polarization',
        description: 'Alex Rivera accounts for 68% of workload and 54 commits, while Jordan Lee has 2 commits and is stalled.',
        severity: 'Critical',
        scoreImpact: -12.0,
        suggestedAction: 'Reassign collision protocol to Marcus and conduct 1-on-1 check-in with Jordan.',
      },
      {
        id: 'rf-3',
        title: 'Communication Channel Decay',
        description: 'Only 4 asynchronous messages posted over the past 6 days; daily standup missed twice.',
        severity: 'Moderate',
        scoreImpact: -7.0,
        suggestedAction: 'Require written 3-bullet standup updates every 48 hours.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 48, event: 'Milestone 2 Kickoff' },
        { day: 2, date: 'Sep 28', score: 45 },
        { day: 3, date: 'Sep 29', score: 42, event: 'Task 101 missed' },
        { day: 4, date: 'Sep 30', score: 39 },
        { day: 5, date: 'Oct 01', score: 36, event: 'Task 102 missed' },
        { day: 6, date: 'Oct 02', score: 33 },
        { day: 7, date: 'Oct 03', score: 32.3, event: 'Current Evaluation' },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 62 },
        { day: 3, date: 'Sep 22', score: 59 },
        { day: 5, date: 'Sep 24', score: 55 },
        { day: 7, date: 'Sep 26', score: 50 },
        { day: 9, date: 'Sep 28', score: 45 },
        { day: 11, date: 'Sep 30', score: 39 },
        { day: 14, date: 'Oct 03', score: 32.3 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 78, event: 'Team Formed' },
        { day: 8, date: 'Sep 11', score: 74 },
        { day: 15, date: 'Sep 18', score: 68 },
        { day: 22, date: 'Sep 25', score: 52 },
        { day: 30, date: 'Oct 03', score: 32.3 },
      ],
    },
  },
  {
    id: 'grp-2',
    name: 'Team Helix',
    projectTitle: 'Hospital Bed & ICU Asset Tracking IoT Gateway',
    courseCode: 'IS420',
    courseName: 'Enterprise Systems Integration',
    lastActivity: '9 days ago (Stalled)',
    lastActivityTimestamp: '2026-09-24T11:00:00Z',
    teamLeader: 'Chloe Martinez',
    repoUrl: 'github.com/eecs-is420/team-helix-iot',
    asanaWorkspace: 'IS420-Team-Helix',
    taskCompletionScore: 30,
    overdueTaskScore: 15,
    memberActivityScore: 25,
    workloadEquityScore: 40,
    communicationScore: 20,
    members: [
      {
        id: 'hm1',
        name: 'Chloe Martinez',
        email: 'c.martinez@university.edu',
        role: 'Systems Architect',
        avatarColor: 'bg-purple-600',
        assignedTasks: 8,
        completedTasks: 3,
        commits: 14,
        prReviews: 2,
        messagesSent: 12,
        lastActive: '9 days ago',
        workloadSharePercent: 42,
        status: 'At-Risk / Disengaged',
      },
      {
        id: 'hm2',
        name: 'David Kim',
        email: 'd.kim@university.edu',
        role: 'Embedded BLE Engineer',
        avatarColor: 'bg-blue-600',
        assignedTasks: 7,
        completedTasks: 2,
        commits: 9,
        prReviews: 1,
        messagesSent: 8,
        lastActive: '10 days ago',
        workloadSharePercent: 30,
        status: 'At-Risk / Disengaged',
      },
      {
        id: 'hm3',
        name: 'Fatima Al-Mansoor',
        email: 'f.almansoor@university.edu',
        role: 'HL7 / FHIR Integration',
        avatarColor: 'bg-rose-600',
        assignedTasks: 6,
        completedTasks: 1,
        commits: 5,
        prReviews: 0,
        messagesSent: 5,
        lastActive: '11 days ago',
        workloadSharePercent: 28,
        status: 'At-Risk / Disengaged',
      },
    ],
    tasks: [
      {
        id: 'ht-1',
        title: 'BLE Beacon RSSI Trilateration Model',
        assigneeId: 'hm2',
        assigneeName: 'David Kim',
        dueDate: 'Sep 21, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 15,
      },
      {
        id: 'ht-2',
        title: 'FHIR Observation RESTful resource handler',
        assigneeId: 'hm3',
        assigneeName: 'Fatima Al-Mansoor',
        dueDate: 'Sep 23, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 14,
      },
      {
        id: 'ht-3',
        title: 'MQTT Broker TLS encryption handshake',
        assigneeId: 'hm1',
        assigneeName: 'Chloe Martinez',
        dueDate: 'Sep 25, 2026',
        status: 'Overdue',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 'ht-4',
        title: 'Hospital ward floorplan SVG mapping',
        assigneeId: 'hm1',
        assigneeName: 'Chloe Martinez',
        dueDate: 'Oct 08, 2026',
        status: 'In Progress',
        priority: 'Low',
        weight: 6,
      },
    ],
    riskFactors: [
      {
        id: 'hrf-1',
        title: 'Prolonged Repository & Workspace Inactivity',
        description: 'Zero code commits and zero task check-ins across all team members for 9 consecutive days.',
        severity: 'Critical',
        scoreImpact: -21.0,
        suggestedAction: 'Issue mandatory instructor summon for emergency academic intervention.',
      },
      {
        id: 'hrf-2',
        title: 'Multiple Overdue Architecture Milestones',
        description: '3 core foundational modules remain incomplete past the Sprint 2 hard deadline.',
        severity: 'Critical',
        scoreImpact: -16.5,
        suggestedAction: 'Require revised sprint contract with descoped deliverables.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 32 },
        { day: 2, date: 'Sep 28', score: 30 },
        { day: 3, date: 'Sep 29', score: 29 },
        { day: 4, date: 'Sep 30', score: 28 },
        { day: 5, date: 'Oct 01', score: 27 },
        { day: 6, date: 'Oct 02', score: 26 },
        { day: 7, date: 'Oct 03', score: 25.8 },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 54 },
        { day: 4, date: 'Sep 23', score: 46 },
        { day: 8, date: 'Sep 27', score: 32 },
        { day: 11, date: 'Sep 30', score: 28 },
        { day: 14, date: 'Oct 03', score: 25.8 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 70 },
        { day: 10, date: 'Sep 14', score: 62 },
        { day: 20, date: 'Sep 24', score: 45 },
        { day: 30, date: 'Oct 03', score: 25.8 },
      ],
    },
  },
  {
    id: 'grp-3',
    name: 'Team Quantum',
    projectTitle: 'Distributed Ledger for Micro-Grid Energy Trading',
    courseCode: 'CS401',
    courseName: 'Capstone Software Engineering',
    lastActivity: 'Yesterday',
    lastActivityTimestamp: '2026-10-02T16:30:00Z',
    teamLeader: 'Siddharth Rao',
    repoUrl: 'github.com/eecs-cs401/team-quantum-energy',
    asanaWorkspace: 'CS401-Team-Quantum',
    taskCompletionScore: 62,
    overdueTaskScore: 55,
    memberActivityScore: 60,
    workloadEquityScore: 52,
    communicationScore: 58,
    members: [
      {
        id: 'qm1',
        name: 'Siddharth Rao',
        email: 's.rao@university.edu',
        role: 'Smart Contract Lead',
        avatarColor: 'bg-emerald-700',
        assignedTasks: 10,
        completedTasks: 7,
        commits: 34,
        prReviews: 8,
        messagesSent: 28,
        lastActive: 'Yesterday',
        workloadSharePercent: 44,
        status: 'Balanced',
      },
      {
        id: 'qm2',
        name: 'Elena Rostova',
        email: 'e.rostova@university.edu',
        role: 'Solidity & Test Auditor',
        avatarColor: 'bg-cyan-600',
        assignedTasks: 8,
        completedTasks: 5,
        commits: 22,
        prReviews: 9,
        messagesSent: 22,
        lastActive: 'Yesterday',
        workloadSharePercent: 28,
        status: 'Balanced',
      },
      {
        id: 'qm3',
        name: 'Lucas Dupont',
        email: 'l.dupont@university.edu',
        role: 'Frontend DApp & Web3 Provider',
        avatarColor: 'bg-amber-600',
        assignedTasks: 8,
        completedTasks: 3,
        commits: 12,
        prReviews: 2,
        messagesSent: 14,
        lastActive: '3 days ago',
        workloadSharePercent: 16,
        status: 'Balanced',
      },
      {
        id: 'qm4',
        name: 'Tara O\'Connor',
        email: 't.oconnor@university.edu',
        role: 'Grid Meter Simulator',
        avatarColor: 'bg-violet-600',
        assignedTasks: 6,
        completedTasks: 2,
        commits: 9,
        prReviews: 1,
        messagesSent: 11,
        lastActive: '2 days ago',
        workloadSharePercent: 12,
        status: 'Balanced',
      },
    ],
    tasks: [
      {
        id: 'qt-1',
        title: 'Double-auction smart contract security fuzz testing',
        assigneeId: 'qm2',
        assigneeName: 'Elena Rostova',
        dueDate: 'Sep 30, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 14,
      },
      {
        id: 'qt-2',
        title: 'ERC-20 Token Settlement logic',
        assigneeId: 'qm1',
        assigneeName: 'Siddharth Rao',
        dueDate: 'Oct 01, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 12,
      },
      {
        id: 'qt-3',
        title: 'MetaMask wallet session connect modal',
        assigneeId: 'qm3',
        assigneeName: 'Lucas Dupont',
        dueDate: 'Oct 05, 2026',
        status: 'In Progress',
        priority: 'Medium',
        weight: 9,
      },
      {
        id: 'qt-4',
        title: 'Solar PV production synthetic data generator',
        assigneeId: 'qm4',
        assigneeName: 'Tara O\'Connor',
        dueDate: 'Oct 07, 2026',
        status: 'In Progress',
        priority: 'Low',
        weight: 7,
      },
    ],
    riskFactors: [
      {
        id: 'qrf-1',
        title: 'Security Audit Milestone Behind Schedule',
        description: 'Smart contract test suite fuzzing is 3 days overdue, holding back testnet deployment.',
        severity: 'Moderate',
        scoreImpact: -8.5,
        suggestedAction: 'Offer TA assistance for Foundry fuzzing test setup.',
      },
      {
        id: 'qrf-2',
        title: 'Uneven Frontend vs Backend Progression',
        description: 'Backend smart contracts are 80% finished while DApp client interface is only 35% ready.',
        severity: 'Moderate',
        scoreImpact: -6.0,
        suggestedAction: 'Pair Lucas with Siddharth for web3 client mocking.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 64 },
        { day: 2, date: 'Sep 28', score: 62 },
        { day: 3, date: 'Sep 29', score: 61 },
        { day: 4, date: 'Sep 30', score: 59 },
        { day: 5, date: 'Oct 01', score: 58 },
        { day: 6, date: 'Oct 02', score: 58 },
        { day: 7, date: 'Oct 03', score: 58.0 },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 68 },
        { day: 5, date: 'Sep 24', score: 65 },
        { day: 9, date: 'Sep 28', score: 62 },
        { day: 14, date: 'Oct 03', score: 58.0 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 72 },
        { day: 12, date: 'Sep 16', score: 69 },
        { day: 22, date: 'Sep 26', score: 63 },
        { day: 30, date: 'Oct 03', score: 58.0 },
      ],
    },
  },
  {
    id: 'grp-4',
    name: 'Team Horizon',
    projectTitle: 'Predictive Wildfire Risk Mapping using Satellite Multispectral Imaging',
    courseCode: 'DS302',
    courseName: 'Data Science Practicum',
    lastActivity: '1 day ago',
    lastActivityTimestamp: '2026-10-02T09:45:00Z',
    teamLeader: 'Nathan Brooks',
    repoUrl: 'github.com/eecs-ds302/team-horizon-wildfire',
    asanaWorkspace: 'DS302-Team-Horizon',
    taskCompletionScore: 68,
    overdueTaskScore: 60,
    memberActivityScore: 64,
    workloadEquityScore: 58,
    communicationScore: 60,
    members: [
      {
        id: 'hm1',
        name: 'Nathan Brooks',
        email: 'n.brooks@university.edu',
        role: 'Data Pipeline & GIS',
        avatarColor: 'bg-teal-600',
        assignedTasks: 9,
        completedTasks: 6,
        commits: 28,
        prReviews: 6,
        messagesSent: 24,
        lastActive: '1 day ago',
        workloadSharePercent: 36,
        status: 'Balanced',
      },
      {
        id: 'hm2',
        name: 'Amina Idris',
        email: 'a.idris@university.edu',
        role: 'Computer Vision / UNet Lead',
        avatarColor: 'bg-pink-600',
        assignedTasks: 8,
        completedTasks: 5,
        commits: 24,
        prReviews: 5,
        messagesSent: 20,
        lastActive: '1 day ago',
        workloadSharePercent: 32,
        status: 'Balanced',
      },
      {
        id: 'hm3',
        name: 'Leo Takahashi',
        email: 'l.takahashi@university.edu',
        role: 'Web Map Tile Server & API',
        avatarColor: 'bg-sky-600',
        assignedTasks: 8,
        completedTasks: 4,
        commits: 16,
        prReviews: 3,
        messagesSent: 15,
        lastActive: '3 days ago',
        workloadSharePercent: 32,
        status: 'Balanced',
      },
    ],
    tasks: [
      {
        id: 'ht-1',
        title: 'Sentinel-2 Cloud Masking automated batching',
        assigneeId: 'hm1',
        assigneeName: 'Nathan Brooks',
        dueDate: 'Sep 29, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 12,
      },
      {
        id: 'ht-2',
        title: 'UNet model checkpoint export to ONNX runtime',
        assigneeId: 'hm2',
        assigneeName: 'Amina Idris',
        dueDate: 'Oct 02, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 14,
      },
      {
        id: 'ht-3',
        title: 'Mapbox GL JS dynamic heatmap vector layers',
        assigneeId: 'hm3',
        assigneeName: 'Leo Takahashi',
        dueDate: 'Oct 06, 2026',
        status: 'In Progress',
        priority: 'Medium',
        weight: 10,
      },
    ],
    riskFactors: [
      {
        id: 'hrf-1',
        title: 'GPU Server Compute Quota Limitation',
        description: 'Sentinel-2 pipeline delayed due to shared departmental GPU cluster queue times.',
        severity: 'Moderate',
        scoreImpact: -5.5,
        suggestedAction: 'Grant secondary cloud credits voucher.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 66 },
        { day: 2, date: 'Sep 28', score: 65 },
        { day: 3, date: 'Sep 29', score: 63 },
        { day: 4, date: 'Sep 30', score: 63 },
        { day: 5, date: 'Oct 01', score: 62 },
        { day: 6, date: 'Oct 02', score: 63 },
        { day: 7, date: 'Oct 03', score: 62.9 },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 70 },
        { day: 7, date: 'Sep 27', score: 66 },
        { day: 14, date: 'Oct 03', score: 62.9 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 75 },
        { day: 15, date: 'Sep 18', score: 71 },
        { day: 30, date: 'Oct 03', score: 62.9 },
      ],
    },
  },
  {
    id: 'grp-5',
    name: 'Team Apex',
    projectTitle: 'Clinical Trial Adverse Event Extraction via LLM Pipelines',
    courseCode: 'DS302',
    courseName: 'Data Science Practicum',
    lastActivity: '25 mins ago',
    lastActivityTimestamp: '2026-10-03T03:10:00Z',
    teamLeader: 'Maya Lin',
    repoUrl: 'github.com/eecs-ds302/team-apex-clinical',
    asanaWorkspace: 'DS302-Team-Apex',
    taskCompletionScore: 92,
    overdueTaskScore: 95,
    memberActivityScore: 88,
    workloadEquityScore: 85,
    communicationScore: 90,
    members: [
      {
        id: 'am1',
        name: 'Maya Lin',
        email: 'm.lin@university.edu',
        role: 'NLP & Evaluation Lead',
        avatarColor: 'bg-emerald-600',
        assignedTasks: 9,
        completedTasks: 8,
        commits: 41,
        prReviews: 14,
        messagesSent: 52,
        lastActive: '25 mins ago',
        workloadSharePercent: 27,
        status: 'Balanced',
      },
      {
        id: 'am2',
        name: 'Lucas Thorne',
        email: 'l.thorne@university.edu',
        role: 'MedDRA Ontology & Parser',
        avatarColor: 'bg-blue-600',
        assignedTasks: 8,
        completedTasks: 8,
        commits: 38,
        prReviews: 12,
        messagesSent: 46,
        lastActive: '1 hour ago',
        workloadSharePercent: 25,
        status: 'Balanced',
      },
      {
        id: 'am3',
        name: 'Zoe Washington',
        email: 'z.washington@university.edu',
        role: 'Validation & Benchmark Metric',
        avatarColor: 'bg-purple-600',
        assignedTasks: 8,
        completedTasks: 7,
        commits: 35,
        prReviews: 15,
        messagesSent: 41,
        lastActive: '3 hours ago',
        workloadSharePercent: 24,
        status: 'Balanced',
      },
      {
        id: 'am4',
        name: 'Kenji Sato',
        email: 'k.sato@university.edu',
        role: 'Clinician UI & Annotation Tool',
        avatarColor: 'bg-teal-600',
        assignedTasks: 8,
        completedTasks: 7,
        commits: 36,
        prReviews: 11,
        messagesSent: 44,
        lastActive: '2 hours ago',
        workloadSharePercent: 24,
        status: 'Balanced',
      },
    ],
    tasks: [
      {
        id: 'at-1',
        title: 'MedDRA v26 hierarchical entity link verification',
        assigneeId: 'am2',
        assigneeName: 'Lucas Thorne',
        dueDate: 'Oct 01, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 12,
      },
      {
        id: 'at-2',
        title: 'Few-shot prompt ablation benchmark (F1 > 0.89)',
        assigneeId: 'am1',
        assigneeName: 'Maya Lin',
        dueDate: 'Oct 02, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 15,
      },
      {
        id: 'at-3',
        title: 'HIPAA compliant de-identification audit harness',
        assigneeId: 'am3',
        assigneeName: 'Zoe Washington',
        dueDate: 'Oct 05, 2026',
        status: 'In Progress',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 'at-4',
        title: 'Interactive clinician highlight review interface',
        assigneeId: 'am4',
        assigneeName: 'Kenji Sato',
        dueDate: 'Oct 08, 2026',
        status: 'In Progress',
        priority: 'Medium',
        weight: 10,
      },
    ],
    riskFactors: [
      {
        id: 'arf-1',
        title: 'High Velocity & Zero Overdue Tasks',
        description: 'Sprint 3 milestones completed 2 days ahead of schedule with robust unit test coverage.',
        severity: 'Notice',
        scoreImpact: 0,
        suggestedAction: 'Invite team to present early architecture demo in lecture.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 86 },
        { day: 2, date: 'Sep 28', score: 87 },
        { day: 3, date: 'Sep 29', score: 88 },
        { day: 4, date: 'Sep 30', score: 89 },
        { day: 5, date: 'Oct 01', score: 90 },
        { day: 6, date: 'Oct 02', score: 90.5 },
        { day: 7, date: 'Oct 03', score: 90.7 },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 82 },
        { day: 5, date: 'Sep 24', score: 84 },
        { day: 9, date: 'Sep 28', score: 87 },
        { day: 14, date: 'Oct 03', score: 90.7 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 79 },
        { day: 12, date: 'Sep 16', score: 83 },
        { day: 22, date: 'Sep 26', score: 86 },
        { day: 30, date: 'Oct 03', score: 90.7 },
      ],
    },
  },
  {
    id: 'grp-6',
    name: 'Team CyberShield',
    projectTitle: 'Zero-Trust Mesh Network Authentication Proxy',
    courseCode: 'CS401',
    courseName: 'Capstone Software Engineering',
    lastActivity: '1 hour ago',
    lastActivityTimestamp: '2026-10-03T02:30:00Z',
    teamLeader: 'Hannah Abbott',
    repoUrl: 'github.com/eecs-cs401/team-cybershield',
    asanaWorkspace: 'CS401-Team-CyberShield',
    taskCompletionScore: 85,
    overdueTaskScore: 90,
    memberActivityScore: 82,
    workloadEquityScore: 80,
    communicationScore: 85,
    members: [
      {
        id: 'cm1',
        name: 'Hannah Abbott',
        email: 'h.abbott@university.edu',
        role: 'Crypto & Protocol Security',
        avatarColor: 'bg-indigo-600',
        assignedTasks: 8,
        completedTasks: 7,
        commits: 38,
        prReviews: 10,
        messagesSent: 35,
        lastActive: '1 hour ago',
        workloadSharePercent: 35,
        status: 'Balanced',
      },
      {
        id: 'cm2',
        name: 'Liam Vance',
        email: 'l.vance@university.edu',
        role: 'eBPF Kernel Probes',
        avatarColor: 'bg-emerald-600',
        assignedTasks: 7,
        completedTasks: 6,
        commits: 32,
        prReviews: 9,
        messagesSent: 31,
        lastActive: '2 hours ago',
        workloadSharePercent: 33,
        status: 'Balanced',
      },
      {
        id: 'cm3',
        name: 'Sofia Rossi',
        email: 's.rossi@university.edu',
        role: 'Certificate Authority & Envoy Proxy',
        avatarColor: 'bg-violet-600',
        assignedTasks: 7,
        completedTasks: 6,
        commits: 30,
        prReviews: 8,
        messagesSent: 29,
        lastActive: '4 hours ago',
        workloadSharePercent: 32,
        status: 'Balanced',
      },
    ],
    tasks: [
      {
        id: 'ct-1',
        title: 'mTLS handshake latency benchmarking (< 1.8ms)',
        assigneeId: 'cm1',
        assigneeName: 'Hannah Abbott',
        dueDate: 'Sep 30, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 12,
      },
      {
        id: 'ct-2',
        title: 'eBPF TC filter packet drop simulation',
        assigneeId: 'cm2',
        assigneeName: 'Liam Vance',
        dueDate: 'Oct 02, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 14,
      },
      {
        id: 'ct-3',
        title: 'Automated SPIFFE ID rotation daemon',
        assigneeId: 'cm3',
        assigneeName: 'Sofia Rossi',
        dueDate: 'Oct 07, 2026',
        status: 'In Progress',
        priority: 'Medium',
        weight: 10,
      },
    ],
    riskFactors: [
      {
        id: 'crf-1',
        title: 'Stable Progression',
        description: 'All cryptographic benchmarks met; zero overdue tasks.',
        severity: 'Notice',
        scoreImpact: 0,
        suggestedAction: 'Maintain current weekly sprint velocity.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 81 },
        { day: 2, date: 'Sep 28', score: 82 },
        { day: 3, date: 'Sep 29', score: 83 },
        { day: 4, date: 'Sep 30', score: 84 },
        { day: 5, date: 'Oct 01', score: 84 },
        { day: 6, date: 'Oct 02', score: 85 },
        { day: 7, date: 'Oct 03', score: 84.9 },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 79 },
        { day: 7, date: 'Sep 27', score: 81 },
        { day: 14, date: 'Oct 03', score: 84.9 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 76 },
        { day: 15, date: 'Sep 18', score: 80 },
        { day: 30, date: 'Oct 03', score: 84.9 },
      ],
    },
  },
  {
    id: 'grp-7',
    name: 'Team Vortex',
    projectTitle: 'Cold-Chain IoT Telemetry & Dynamic Fleet Dispatcher',
    courseCode: 'ENG480',
    courseName: 'Industrial IoT Systems',
    lastActivity: '4 days ago (Synced from Asana)',
    lastActivityTimestamp: '2026-09-29T14:20:00Z',
    teamLeader: 'Maya Lin',
    repoUrl: 'github.com/vortex-iot/cold-chain-router',
    asanaWorkspace: 'Asana: IoT-Logistics-Sprint-4',
    taskCompletionScore: 30,
    overdueTaskScore: 15,
    memberActivityScore: 28,
    workloadEquityScore: 32,
    communicationScore: 25,
    members: [
      {
        id: 'm-v1',
        name: 'Maya Lin',
        email: 'm.lin@university.edu',
        role: 'Tech Lead & Hardware Integration',
        avatarColor: 'bg-rose-600',
        assignedTasks: 8,
        completedTasks: 3,
        commits: 41,
        prReviews: 5,
        messagesSent: 26,
        lastActive: '4 days ago',
        workloadSharePercent: 64,
        status: 'Overloaded',
      },
      {
        id: 'm-v2',
        name: 'Lucas Vance',
        email: 'l.vance@university.edu',
        role: 'Backend API Engineer',
        avatarColor: 'bg-amber-600',
        assignedTasks: 6,
        completedTasks: 0,
        commits: 4,
        prReviews: 0,
        messagesSent: 5,
        lastActive: '6 days ago',
        workloadSharePercent: 20,
        status: 'At-Risk / Disengaged',
      },
      {
        id: 'm-v3',
        name: 'Zoe Chen',
        email: 'z.chen@university.edu',
        role: 'Mobile Telemetry & Dashboard',
        avatarColor: 'bg-slate-600',
        assignedTasks: 5,
        completedTasks: 0,
        commits: 2,
        prReviews: 1,
        messagesSent: 3,
        lastActive: '8 days ago',
        workloadSharePercent: 16,
        status: 'At-Risk / Disengaged',
      },
    ],
    tasks: [
      {
        id: 't-v1',
        title: 'MQTT Broker TLS mutual authentication setup',
        assigneeId: 'm-v1',
        assigneeName: 'Maya Lin',
        dueDate: 'Sep 21, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-v2',
        title: 'Geofenced temperature excursion event publisher',
        assigneeId: 'm-v1',
        assigneeName: 'Maya Lin',
        dueDate: 'Sep 24, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-v3',
        title: 'LoRaWAN sensor gateway failover test suite',
        assigneeId: 'm-v1',
        assigneeName: 'Maya Lin',
        dueDate: 'Sep 27, 2026',
        status: 'Completed',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 't-v4',
        title: 'Driver mobile app offline GPS cache buffer',
        assigneeId: 'm-v3',
        assigneeName: 'Zoe Chen',
        dueDate: 'Sep 25, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-v5',
        title: 'Cold-storage shipment audit trail database schema',
        assigneeId: 'm-v2',
        assigneeName: 'Lucas Vance',
        dueDate: 'Sep 26, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-v6',
        title: 'Real-time WebSocket alerting relay service',
        assigneeId: 'm-v2',
        assigneeName: 'Lucas Vance',
        dueDate: 'Sep 28, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 12,
      },
      {
        id: 't-v7',
        title: 'PostgreSQL read-replica query optimizer',
        assigneeId: 'm-v2',
        assigneeName: 'Lucas Vance',
        dueDate: 'Sep 29, 2026',
        status: 'Overdue',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 't-v8',
        title: 'iOS client Bluetooth BLE sensor beacon pairing',
        assigneeId: 'm-v3',
        assigneeName: 'Zoe Chen',
        dueDate: 'Sep 30, 2026',
        status: 'Overdue',
        priority: 'High',
        weight: 12,
      },
      {
        id: 't-v9',
        title: 'Battery drain telemetry profiling on edge nodes',
        assigneeId: 'm-v1',
        assigneeName: 'Maya Lin',
        dueDate: 'Oct 01, 2026',
        status: 'Overdue',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 't-v10',
        title: 'End-to-end integration demo rehearsal',
        assigneeId: 'm-v1',
        assigneeName: 'Maya Lin',
        dueDate: 'Oct 08, 2026',
        status: 'In Progress',
        priority: 'High',
        weight: 15,
      },
    ],
    riskFactors: [
      {
        id: 'rf-v1',
        title: 'Severe Asana Milestone Backlog (6 Overdue Tasks)',
        description: '60% of all sprint deliverables in Asana are past due date, severely depressing project health.',
        severity: 'Critical',
        scoreImpact: -18.5,
        suggestedAction: 'Hold emergency triage with Maya to descope mobile BLE requirements.',
      },
      {
        id: 'rf-v2',
        title: 'Extreme Workload Polarization & Inactivity',
        description: 'Lucas and Zoe have not pushed code or completed tasks in 6+ days; Maya is carrying 64% of total output.',
        severity: 'Critical',
        scoreImpact: -12.0,
        suggestedAction: 'Require individual sprint progress logs and check in on teammate blockers.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 36.2 },
        { day: 3, date: 'Sep 29', score: 31.5 },
        { day: 5, date: 'Oct 01', score: 28.0 },
        { day: 7, date: 'Oct 03', score: 25.7, event: '6 Overdue Asana Tasks Detected' },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 54.0 },
        { day: 7, date: 'Sep 27', score: 36.2 },
        { day: 14, date: 'Oct 03', score: 25.7 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 68.0 },
        { day: 15, date: 'Sep 18', score: 58.5 },
        { day: 30, date: 'Oct 03', score: 25.7 },
      ],
    },
  },
  {
    id: 'grp-8',
    name: 'Team Solaria',
    projectTitle: 'Smart Microgrid Energy Arbitrage & Battery Optimization',
    courseCode: 'CS450',
    courseName: 'Distributed Energy Systems',
    lastActivity: '22m ago (Synced from Asana)',
    lastActivityTimestamp: '2026-10-03T04:38:00Z',
    teamLeader: 'Elena Rostova',
    repoUrl: 'github.com/solaria-grid/microgrid-arbitrage',
    asanaWorkspace: 'Asana: GreenTech-Microgrid-2026',
    taskCompletionScore: 92,
    overdueTaskScore: 100,
    memberActivityScore: 90,
    workloadEquityScore: 88,
    communicationScore: 92,
    members: [
      {
        id: 'm-s1',
        name: 'Elena Rostova',
        email: 'e.rostova@university.edu',
        role: 'Tech Lead & Optimization Modeling',
        avatarColor: 'bg-emerald-600',
        assignedTasks: 8,
        completedTasks: 7,
        commits: 46,
        prReviews: 14,
        messagesSent: 42,
        lastActive: '22m ago',
        workloadSharePercent: 35,
        status: 'Balanced',
      },
      {
        id: 'm-s2',
        name: 'Kai Zhang',
        email: 'k.zhang@university.edu',
        role: 'Distributed Consensus & Grid Telemetry',
        avatarColor: 'bg-blue-600',
        assignedTasks: 7,
        completedTasks: 6,
        commits: 41,
        prReviews: 12,
        messagesSent: 38,
        lastActive: '1 hour ago',
        workloadSharePercent: 33,
        status: 'Balanced',
      },
      {
        id: 'm-s3',
        name: 'Priya Patel',
        email: 'p.patel@university.edu',
        role: 'Price Forecasting & ML Pipeline',
        avatarColor: 'bg-teal-600',
        assignedTasks: 7,
        completedTasks: 6,
        commits: 39,
        prReviews: 11,
        messagesSent: 35,
        lastActive: '3 hours ago',
        workloadSharePercent: 32,
        status: 'Balanced',
      },
    ],
    tasks: [
      {
        id: 't-s1',
        title: 'Day-ahead wholesale electricity price prophet model',
        assigneeId: 'm-s3',
        assigneeName: 'Priya Patel',
        dueDate: 'Sep 18, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-s2',
        title: 'Linear programming battery dispatch solver',
        assigneeId: 'm-s1',
        assigneeName: 'Elena Rostova',
        dueDate: 'Sep 21, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-s3',
        title: 'Inverter SCADA protocol adapter (Modbus TCP)',
        assigneeId: 'm-s2',
        assigneeName: 'Kai Zhang',
        dueDate: 'Sep 24, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 15,
      },
      {
        id: 't-s4',
        title: 'Microgrid islanding seamless disconnect simulator',
        assigneeId: 'm-s2',
        assigneeName: 'Kai Zhang',
        dueDate: 'Sep 27, 2026',
        status: 'Completed',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 't-s5',
        title: 'Lithium iron phosphate battery degradation constraint matrix',
        assigneeId: 'm-s1',
        assigneeName: 'Elena Rostova',
        dueDate: 'Sep 29, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 12,
      },
      {
        id: 't-s6',
        title: 'Solar irradiance rooftop array forecasting pipeline',
        assigneeId: 'm-s3',
        assigneeName: 'Priya Patel',
        dueDate: 'Oct 01, 2026',
        status: 'Completed',
        priority: 'High',
        weight: 12,
      },
      {
        id: 't-s7',
        title: 'Grid tariff schedule dynamic ingestion API',
        assigneeId: 'm-s2',
        assigneeName: 'Kai Zhang',
        dueDate: 'Oct 02, 2026',
        status: 'Completed',
        priority: 'Medium',
        weight: 10,
      },
      {
        id: 't-s8',
        title: 'Hardware-in-the-loop validation test bench',
        assigneeId: 'm-s1',
        assigneeName: 'Elena Rostova',
        dueDate: 'Oct 07, 2026',
        status: 'In Progress',
        priority: 'High',
        weight: 15,
      },
    ],
    riskFactors: [
      {
        id: 'rf-s1',
        title: 'Nominal Asana Velocity (0 Overdue Deliverables)',
        description: 'All milestones are tracking on or ahead of sprint schedule in Asana with active participation.',
        severity: 'Notice',
        scoreImpact: 0,
        suggestedAction: 'Maintain current weekly review cadence.',
      },
      {
        id: 'rf-s2',
        title: 'Exemplary Workload Equity & Review Turnaround',
        description: 'Workload distribution is within 3% parity across all 3 members with prompt code reviews.',
        severity: 'Notice',
        scoreImpact: 0,
        suggestedAction: 'Candidate team for capstone demonstration showcase.',
      },
    ],
    trends: {
      sevenDays: [
        { day: 1, date: 'Sep 27', score: 89.0 },
        { day: 3, date: 'Sep 29', score: 90.5 },
        { day: 5, date: 'Oct 01', score: 92.0 },
        { day: 7, date: 'Oct 03', score: 93.0, event: 'Sprint 3 Inverter SCADA Validated' },
      ],
      fourteenDays: [
        { day: 1, date: 'Sep 20', score: 86.0 },
        { day: 7, date: 'Sep 27', score: 89.0 },
        { day: 14, date: 'Oct 03', score: 93.0 },
      ],
      thirtyDays: [
        { day: 1, date: 'Sep 04', score: 82.5 },
        { day: 15, date: 'Sep 18', score: 87.0 },
        { day: 30, date: 'Oct 03', score: 93.0 },
      ],
    },
  },
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'alt-vortex',
    groupId: 'grp-7',
    groupName: 'Team Vortex',
    courseCode: 'ENG480',
    riskLevel: 'High',
    healthScore: 25.7,
    contributingFactors: 'Asana Alert: 6 overdue tasks past milestone deadline; team communication stalled for 96 hours.',
    timestamp: '10m ago',
    read: false,
  },
  {
    id: 'alt-1',
    groupId: 'grp-2',
    groupName: 'Team Helix',
    courseCode: 'IS420',
    riskLevel: 'High',
    healthScore: 25.8,
    contributingFactors: 'Critical Inactivity: 9 days without commits or task updates; 3 overdue sprint milestones.',
    timestamp: '25m ago',
    read: false,
  },
  {
    id: 'alt-2',
    groupId: 'grp-1',
    groupName: 'Team Nova',
    riskLevel: 'High',
    courseCode: 'CS401',
    healthScore: 32.3,
    contributingFactors: 'Severe Workload Polarization (Alex: 68%, Jordan: stalled); 3 high-priority tasks overdue.',
    timestamp: '2h ago',
    read: false,
  },
  {
    id: 'alt-3',
    groupId: 'grp-3',
    groupName: 'Team Quantum',
    riskLevel: 'Medium',
    courseCode: 'CS401',
    healthScore: 58.0,
    contributingFactors: 'Smart contract test fuzzing milestone 3 days overdue; low PR review turnaround.',
    timestamp: '5h ago',
    read: false,
  },
  {
    id: 'alt-4',
    groupId: 'grp-4',
    groupName: 'Team Horizon',
    riskLevel: 'Medium',
    courseCode: 'DS302',
    healthScore: 62.9,
    contributingFactors: 'Compute quota bottleneck on Sentinel-2 processing; standup frequency dropped.',
    timestamp: 'Yesterday',
    read: true,
  },
  {
    id: 'alt-5',
    groupId: 'grp-5',
    groupName: 'Team Apex',
    riskLevel: 'Low',
    courseCode: 'DS302',
    healthScore: 90.7,
    contributingFactors: 'Milestone 3 delivered ahead of schedule; optimal 4-member workload balance.',
    timestamp: '2 days ago',
    read: true,
  },
];

export const INITIAL_SETTINGS: UserSettings = {
  emailNotifications: true,
  highRiskAlerts: true,
  dailyDigest: true,
  asanaWebhookSync: true,
};
